src/config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import IndexView, UserLoginView, UserLogoutView, UserRegistrationView, send_test_email

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", IndexView.as_view(), name="index"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("send_test_email/", send_test_email, name="send_test_email"),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
]

src/groups/urls.py
from django.urls import path
from groups.views import get_groups, GroupUpdateView, GroupCreate, GroupDeleteView

app_name = "groups"

urlpatterns = [
    path("", get_groups, name="get_groups"),
    path("create/", GroupCreate.as_view(), name="create_group"),
    path("update/<int:pk>/", GroupUpdateView.as_view(), name="update_group"),
    path("delete/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"),
]

src/students/urls.py
from django.urls import path
from students.views import get_students, StudentCreate, StudentUpdateView, StudentDeleteView

app_name = "students"

urlpatterns = [
    path("", get_students, name="get_students"),
    path("create/", StudentCreate.as_view(), name="create_student"),
    path("update/<uuid:uuid>/", StudentUpdateView.as_view(), name="update_student"),
    path("delete/<uuid:uuid>/", StudentDeleteView.as_view(), name="delete_student"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import TeacherCreate, TeacherUpdateView, get_teachers, TeacherDeleteView

app_name = "teachers"

urlpatterns = [
    path("", get_teachers, name="get_teachers"),
    path("create/", TeacherCreate.as_view(), name="create_teacher"),
    path("update/<int:pk>/", TeacherUpdateView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", TeacherDeleteView.as_view(), name="delete_teacher"),
]

src/templates/create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <form method="POST" style="width: 25em;  margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary" value="Create">Create</button>
    </form>
</div>
{% endblock content %}

src/templates/delete.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <form method="POST" style="width: 25em;  margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary" value="Delete">Delete</button>
    </form>
</div>
{% endblock content %}

src/templates/group_list.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <form>
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <div class="input-group">
                    <input class="form-control" id="search" type="search" placeholder="Search" name="search">
                    <button class="btn btn-outline-secondary" type="button" style="float: right;">Search</button>
                </div>
            </tr>
            <tr>
                <th scope="col">#</th>
                <th>Course name</th>
                <th>Course id</th>
                <th>Max count of students</th>
                <th>Lesson count</th>
                <th>Homework count</th>
                <th>Start date course</th>
                <th>End date course</th>
                <th>Group gpa</th>
            </tr>
            </thead>
            <tbody>
            {% for group in groups %}
            <tr>
                <th>{{group.course_name}}</th>
                <th>{{group.course_id}}</th>
                <th>{{group.max_count_of_students}}</th>
                <th>{{group.lesson_count}}</th>
                <th>{{group.homework_count}}</th>
                <th>{{group.start_date_course}}</th>
                <th>{{group.end_date_course}}</th>
                <th>{{group.group_gpa}}</th>
                <th>
                    <a type="button" class="btn btn-warning"
                       href="{% url 'groups:update_group' group.id %}">Edit</a>
                </th>
                <th>
                    <a type="button" class="btn btn-danger"
                       href="{% url 'groups:delete_group' group.id %}"
                       onclick="return confirm('Are you sure you want to delete this student?')">Delete</a>
                </th>

            </tr>
            {% endfor %}
            </tbody>
        </table>
        <!--        <table class="table table-dark table-striped">-->
        <!--            table class="table">-->
        <!--            {{students}}-->
        <!--        </table>-->
    </form>
</div>
{% endblock content %}

src/templates/index.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Cover Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/cover/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">


    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">My LMS</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>

                {% if user.is_authenticated %}
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="studentsDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Students
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="studentsDropdown">
                        <li><a class="dropdown-item" href="{% url 'students:get_students' %}">View Students</a></li>
                        <li><a class="dropdown-item" href="{% url 'students:create_student' %}">Add new student</a></li>
                    </ul>
                </div>

                <!-- Teachers dropdown -->
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="teachersDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Teachers
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="teachersDropdown">
                        <li><a class="dropdown-item" href="{% url 'teachers:get_teachers' %}">View Teachers</a></li>
                        <li><a class="dropdown-item" href="{% url 'teachers:create_teacher' %}">Add new teacher</a></li>
                    </ul>
                </div>

                <!-- Groups dropdown -->
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="groupsDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Groups
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="groupsDropdown">
                        <li><a class="dropdown-item" href="{% url 'groups:get_groups' %}">View Groups</a></li>
                        <li><a class="dropdown-item" href="{% url 'groups:create_group' %}">Add new group</a></li>
                    </ul>
                </div>
                {% endif %}
                <a href="#" class="nav-link d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="mdo" class="rounded-circle" width="32" height="32">
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                    {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="">{{ user.first_name|title }} {{ user.last_name|title }}</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><a class="dropdown-item" href="#">Change password</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'register' %}">Registration</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Reset password</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="">Registration via Google</a></li>
                    <li><a class="dropdown-item" href="#">Registration via Facebook</a></li>
                    {% endif %}


                </ul>


            </nav>
        </div>
    </header>


    <main class="px-3">
        {% block content %}
        <h1></h1>
        <p class="lead">Ноубади беливз ин ю Ю лост егейн енд егейн енд егейн Зе лайтс ар кат оффБат ю стил лукинг ет йор
            дримРепит ит еври дей енд сей ту йорселф Итс нот овер антил ай вин!!!!!!!!</p>
        <p class="lead">
            <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-black">Let's do it</a>
        </p>
        <img src="{% static 'img/pic.jpeg' %}" alt="No image">
        {% endblock %}
    </main>

    <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
    </footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>

src/templates/student_list.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <form>
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <div class="input-group">
                    <input class="form-control" id="search" type="search" placeholder="Search" name="search">
                    <button class="btn btn-outline-secondary" type="button" style="float: right;">Search</button>
                </div>
            </tr>
            <tr>
                <th scope="col">#</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th>Birth date</th>
                <th>Age</th>
                <th>Grade</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for student in students %}
                <tr>
                    <th>{{student.id}}</th>
                    <th>{{student.first_name}}</th>
                    <th>{{student.last_name}}</th>
                    <th>{{student.email}}</th>
                    {% if student.birth_date %}
                    <th>{{student.birth_date}}</th>
                    <th>{{student.age}}</th>
                    {% else %}
                    <th>Not available</th>
                    <th>Invalid birth date</th>
                    {% endif %}
                    <th>{{student.grade}}</th>
                    <th>
                        <a type="button" class="btn btn-warning"
                           href="{% url 'students:update_student' student.uuid %}">Edit</a>
                    </th>
                    <th>
                        <a type="button" class="btn btn-danger"
                           href="{% url 'students:delete_student' student.uuid %}"
                           onclick="return confirm('Are you sure you want to delete this student?')">Delete</a>
                    </th>

                </tr>
            {% endfor %}
            </tbody>
        </table>
        <!--        <table class="table table-dark table-striped">-->
        <!--            table class="table">-->
        <!--            {{students}}-->
        <!--        </table>-->
    </form>
</div>
{% endblock content %}

src/templates/teacher_list.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <form>
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <div class="input-group">
                    <input class="form-control" id="search" type="search" placeholder="Search" name="search">
                    <button class="btn btn-outline-secondary" type="button" style="float: right;">Search</button>
                </div>
            </tr>
            <tr>
                <th scope="col">#</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th>Birth date</th>
                <th>Age</th>
                <th>Grade</th>
                <th>Department</th>
                <th>Group</th>
                <th>Student count</th>
                <th>Group count</th>

                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for teacher in teachers %}
            <tr>
                <th>{{teacher.id}}</th>
                <th>{{teacher.first_name}}</th>
                <th>{{teacher.last_name}}</th>
                <th>{{teacher.email}}</th>
                {% if teacher.birth_date %}
                <th>{{teacher.birth_date}}</th>
                <th>{{teacher.age}}</th>
                {% else %}
                <th>Not available</th>
                <th>Invalid birth date</th>
                {% endif %}
                <th>{{teacher.grade}}</th>
                <th>{{teacher.department}}</th>
                <th>{{teacher.group}}</th>
                <th>{{teacher.student_count}}</th>
                <th>{{teacher.group_count}}</th>


                <th>
                    <a type="button" class="btn btn-warning"
                       href="{% url 'teachers:update_teacher' teacher.id %}">Edit</a>
                </th>
                <th>
                    <a type="button" class="btn btn-danger"
                       href="{% url 'teachers:delete_teacher' teacher.id %}"
                       onclick="return confirm('Are you sure you want to delete this student?')">Delete</a>
                </th>

            </tr>
            {% endfor %}
            </tbody>
        </table>
        <!--        <table class="table table-dark table-striped">-->
        <!--            table class="table">-->
        <!--            {{students}}-->
        <!--        </table>-->
    </form>
</div>
{% endblock content %}

src/templates/update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <form method="POST" style="width: 25em;  margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary" value="Update">Submit</button>
    </form>
</div>
{% endblock content %}